version: '2'

volumes:
  algorand_data:

services:
  algorand_mainnet:
    build: ./
    restart: always
    volumes: 
      - algorand_data:/algorand
    environment:
      VIRTUAL_HOST: YOUR_HOST_URL
      LETSENCRYPT_HOST: YOUR_HOST_URL

networks:
  default:
    external:
      name: nginx_default